import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const require = createRequire(import.meta.url);
const root = JSON.parse(readFileSync("package.json", "utf8"));
const seen = new Set();
const notices = [
  "ATLYN PROCESS LENS - THIRD-PARTY NOTICES",
  "Generated from the installed locked production dependency graph.",
  "Keep this file alongside the .pbiviz when distributing it.",
  "The following licenses apply to the named third-party components, not to the Atlyn product as a whole.",
  ""
];
function visit(name, from) {
  const path = require.resolve(`${name}/package.json`, { paths: [from] });
  const directory = dirname(path);
  const pkg = JSON.parse(readFileSync(path, "utf8"));
  const key = `${pkg.name}@${pkg.version}`;
  if (seen.has(key)) return;
  seen.add(key);
  const licensePath = ["LICENSE", "LICENSE.md", "LICENSE.txt", "license", "license.md"].map(file => join(directory, file)).find(existsSync);
  if (!licensePath) throw new Error(`Review required: no license text found for ${key}`);
  notices.push("=".repeat(72), key, `Declared license: ${pkg.license ?? "UNDECLARED"}`,
    `Source: ${typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url ?? pkg.homepage ?? "See npm package"}`,
    "", readFileSync(licensePath, "utf8"), "");
  for (const dependency of Object.keys(pkg.dependencies ?? {}).sort()) visit(dependency, directory);
}
for (const dependency of Object.keys(root.dependencies ?? {}).sort()) visit(dependency, resolve("."));
const content = notices.join("\n").trimEnd() + "\n";
writeFileSync("THIRD-PARTY-NOTICES.txt", content);
writeFileSync("src/notices.ts", `// Generated by npm run notices from locked production dependency licenses.\nexport const THIRD_PARTY_NOTICES = ${JSON.stringify(content)};\n`);
console.log(`Wrote notices for ${seen.size} production dependency packages.`);
